name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build
      - run: docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/cms-api .
      - run: docker push gcr.io/${{ secrets.GCP_PROJECT }}/cms-api
      - run: |
          gcloud auth activate-service-account --key-file=${{ secrets.GCP_SA_KEY }}
          gcloud config set project ${{ secrets.GCP_PROJECT }}
          kubectl apply -f k8s/